from __future__ import annotations

from backend.config.paths import (
    FINAL_METEO_DIR,
    FINAL_STATIC_DIR,
    INT_INDEX_DIR,
    OUT_INDEX_NC_DIR,
)

DEFAULT_SPECIES = ("porcini", "finferli")

METEO_RECENT_NC = FINAL_METEO_DIR / "meteo_recent_003deg.nc"
TERRAIN_STATIC_NC = FINAL_STATIC_DIR / "terrain_static_003deg.nc"

INDEX_FEATURE_WINDOW_DAYS = 19
TRIGGER_LAG_DAYS = tuple(range(7, 17))
TRIGGER_RAIN_WINDOW_DAYS = 3
MIN_SCORE_TO_EXPORT = 3.0

RECOVERY_LOOKBACK_DAYS = 6
RECOVERY_LAG_WEIGHTS = (0.50, 0.42, 0.34, 0.26, 0.18, 0.10)
RECOVERY_PRESENCE_SCORE_THRESHOLD = 70.0
RECOVERY_MAX_PRESENCE_BOOST = 25.0
RECOVERY_DRY_HISTORY_SCORE_RANGE = (25.0, 55.0)
RECOVERY_RAIN_SEED_BASE_SCORE_RANGE = (25.0, 55.0)
RECOVERY_RAIN_SEED_TARGET_SCORE = 65.0
RECOVERY_RAIN_SEED_MAX_BOOST = 12.0
RECOVERY_COMPONENT_GATE_BASE = 0.65
RECOVERY_RAIN_SEED_TRIGGER_RANGE = (0.30, 0.70)
RECOVERY_RAIN_SEED_MOISTURE_RANGE = (0.25, 0.65)
RECOVERY_RAIN_SEED_STRESS_RANGE = (0.25, 0.75)
RECOVERY_RAIN_SEED_HABITAT_RANGE = (0.15, 0.45)

INDEX_FEATURES_TEMPLATE = INT_INDEX_DIR / "index_features_{date}.nc"
INDEX_OUTPUT_TEMPLATE = OUT_INDEX_NC_DIR / "funghi_index_{date}.nc"
